### ISSUE TITLE
Clock reset.

### ISSUE THREAD

**Issue by nicknamemok** [barlowtj48/flipclock#2]
Hey your project looks awesome! I'm just peeking at your code and wanted to ask something.
If you unplug the clock without putting it at 'rest' position (i.e. holding the button for 10 seconds), does the clock function properly after re-plugging it in? Thanks!

**Comment by barlowtj48** [comment]
Without some sort of sensor, unfortunately unplugging it before a 'rest' position means you've got to do some manual flapping to get it back to "0000". It was an idea that another person had to use a hall-effect sensor and some small magnets to make it detectable, and then automatic, but I haven't implemented that.

**Comment by nicknamemok** [comment]
Thanks for the response!
Hall-effect or an encoder would both do the trick, but then that would kind of take the budget of this thing too high.
I am thinking maybe microswitches could do the trick? But I'm not sure, we will see!
